### ISSUE TITLE
Bruh Moment when installing py5canvas on windows 10

### ISSUE THREAD

**Issue by IthronMinya** [colormotor/py5canvas#4]
Close window event
Saving params

Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x000001D28C663EB0>
Traceback (most recent call last):
  File "D:\EACVA\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 745, in f
    result = event_handler(msg, wParam, lParam)
  File "D:\EACVA\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 1074, in _event_close
    self.dispatch_event('on_close')
  File "D:\EACVA\venv\lib\site-packages\pyglet\window\__init__.py", line 672, in dispatch_event
    super().dispatch_event(*args)
  File "D:\EACVA\venv\lib\site-packages\pyglet\event.py", line 380, in dispatch_event
    if handler(*args):
  File "d:\py5canvas\py5canvas\run_sketch.py", line 1073, in on_close
    close()
  File "d:\py5canvas\py5canvas\run_sketch.py", line 1060, in close
    sketch.params.save()
  File "d:\py5canvas\py5canvas\sketch_params.py", line 153, in save
    save_json(data, path)
  File "d:\py5canvas\py5canvas\sketch_params.py", line 68, in save_json
    json.dump(data, fp, indent=4, sort_keys=False, cls=encoder)
  File "C:\Users\Michael Stroh\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Michael Stroh\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\Michael Stroh\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Michael Stroh\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\Michael Stroh\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "d:\py5canvas\py5canvas\sketch_params.py", line 49, in default
    elif isinstance(obj, (np.float_, np.float16, np.float32,
  File "D:\EACVA\venv\lib\site-packages\numpy\__init__.py", line 411, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

**Comment by colormotor** [comment]
should be fixed!
